Master job and bigsky
OpenOmics/Dmux pull request #24
Opened 2023-11-15 18:34 UTC by rroutsong

Major change from pip-centric packaging to git submodule packaging. Will need to update submodule once that PR is merged.

Address https://github.com/OpenOmics/Dmux/issues/9 https://github.com/OpenOmics/Dmux/issues/8 https://github.com/OpenOmics/Dmux/issues/7 https://github.com/OpenOmics/Dmux/issues/13 and https://github.com/OpenOmics/Dmux/issues/16

Given --dry_run or --local, jobs are not submitted to slurm. 

Attached is example dry run output.

Example output on biowulf: `/data/RTB_GRS/dev/Dmux/test_ngsqc2`
Example output on bigsky: `/gs1/Scratch/routsongrm/dev/Dmux/test_dmux`

Dry run example output is attached [here](https://github.com/OpenOmics/Dmux/files/13368111/test_dry_run.txt).

2023-11-16 23:40 UTC, skchronicles requested changes
Hey @rroutsong,

Everything looks great! I just have a few minor comments. The only thing I think we may need to change or think about before merging everything is the commit of the 5MB RPM package for BCL convert. We may need to permanently remove this from the git commit history as it will dramatically increase the size of the project's commit history.

2023-11-16 23:40 UTC, skchronicles commented on .gitmodules
Thank you for adding this!

2023-11-16 23:40 UTC, skchronicles commented on .tests/ngs_qa_qc/WT_S1.R1.fastq.gz
I usually keep these for dry-running the pipeline but if we plan to support mutually exclusive mixed inputs (BCL vs. FastQ file) we may want to add these back.

2023-11-16 23:40 UTC, skchronicles commented on INSTALL.md
We may want to add more detailed instructions for users setting up or installing the pipeline.

2023-11-16 23:40 UTC, skchronicles commented on docker/NGS_QC/fastq_screen.conf
This file should ideally be created on the fly, or we need to provide instructions for setting up the pipeline on other clusters.

2023-11-16 23:40 UTC, skchronicles commented on docker/demux/bcl-convert-3.6.3-1.el7.x86_64.rpm
Did you mean to commit this file? It's pretty large (>1MB).

2023-11-17 16:21 UTC, rroutsong commented on INSTALL.md
Yeah there is a good amount of documentation I need to update. I can work that in to a single PR next.

2023-11-17 16:32 UTC, skchronicles commented on docker/NGS_QC/fastq_screen.conf
Okay, perfect, thank you for the clarification. That sounds good!

2023-11-17 16:35 UTC, skchronicles commented on .tests/ngs_qa_qc/WT_S1.R1.fastq.gz
No worries, we can always touch those files in the ci prior to the dry-run later. Let's keep it like this for now.

2023-11-17 16:36 UTC, skchronicles approved these changes
Thank you for addressing my comments and questions! Everything looks great. Thank you for the updates!

2023-11-17 16:36 UTC, merged